# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-19 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfo',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='subclass_details',
            name='deviceInfo',
        ),
        migrations.RemoveField(
            model_name='subclass_details',
            name='organization',
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organization'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='website',
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cname',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(max_length=20, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='device',
            field=models.IntegerField(max_length=8, null=True, validators=['d', 'e', 'v', 'i', 'c', 'e']),
        ),
        migrations.AlterField(
            model_name='organization',
            name='district',
            field=models.CharField(max_length=50, null=True, verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ename',
            field=models.CharField(max_length=50, null=True, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='province',
            field=models.CharField(max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='room',
            field=models.IntegerField(max_length=8, null=True, validators=['r', 'o', 'o', 'm']),
        ),
        migrations.AlterField(
            model_name='organization',
            name='telphone',
            field=models.CharField(max_length=30, null=True, validators=['t', 'e', 'l', 'p', 'h', 'o', 'n', 'e']),
        ),
        migrations.DeleteModel(
            name='DeviceInfo',
        ),
        migrations.DeleteModel(
            name='subclass_details',
        ),
    ]
