# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-14 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclass_details',
            name='State',
            field=models.CharField(choices=[('to poy', 'to poy '), ('To be paid', 'To be paid'), ('Refund', 'Refund')], default='To be paid', max_length=10, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='subclass_details',
            name='endtime',
            field=models.DateTimeField(auto_now=True, verbose_name='Payment time'),
        ),
        migrations.AlterField(
            model_name='subclass_details',
            name='paymenttime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Payment time'),
        ),
    ]
