# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-20 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xproject', '0002_auto_20181220_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='organization',
        ),
    ]
