# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-18 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xproject', '0002_auto_20181214_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceID', models.CharField(max_length=20, unique=True, verbose_name='DeviceID')),
                ('Eey', models.CharField(max_length=30, verbose_name='Eey')),
                ('eKey', models.CharField(max_length=30, verbose_name='eKey')),
                ('ADDR', models.CharField(max_length=30, verbose_name='ADDR')),
                ('MACaddress', models.CharField(max_length=30, null=True, verbose_name='MACaddress')),
                ('CCID', models.CharField(max_length=30, null=True, verbose_name='CCID')),
                ('RegTimes', models.DateTimeField(auto_now_add=True, verbose_name='RegTimes')),
                ('RecTimes', models.DateTimeField(auto_now=True, verbose_name='RecTimes')),
                ('BeatTimes', models.DateTimeField(auto_now=True, verbose_name='BeatTimes')),
                ('subclass_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xproject.subclass_details')),
            ],
            options={
                'verbose_name': 'DeviceInfo',
                'verbose_name_plural': 'DeviceInfo',
            },
        ),
    ]
