# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-20 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xproject', '0003_remove_normaluser_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('starttime', models.CharField(max_length=20, verbose_name='start time')),
                ('endtime', models.CharField(max_length=20, null=True, verbose_name='endtime')),
            ],
            options={
                'verbose_name': 'price',
                'verbose_name_plural': 'price',
            },
        ),
        migrations.AlterModelOptions(
            name='normaluser',
            options={'verbose_name': 'USERS', 'verbose_name_plural': 'USERS'},
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='AlarmMOB',
            field=models.IntegerField(null=True, verbose_name='AlarmMOB'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='device',
            field=models.IntegerField(null=True, verbose_name='device'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='room',
            field=models.IntegerField(null=True, verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='subclass_details',
            name='Duration',
            field=models.IntegerField(verbose_name='Transaction duration'),
        ),
        migrations.AlterField(
            model_name='subclass_details',
            name='POnumber',
            field=models.IntegerField(verbose_name='Payment order number'),
        ),
        migrations.AddField(
            model_name='price',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xproject.Organization'),
        ),
    ]
