# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-18 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xproject', '0003_deviceinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfo',
            name='subclass_detail',
        ),
        migrations.AddField(
            model_name='subclass_details',
            name='deviceInfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xproject.DeviceInfo'),
            preserve_default=False,
        ),
    ]
