# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-19 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xproject', '0003_ss'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceID', models.CharField(max_length=20, unique=True, verbose_name='DeviceID')),
                ('Eey', models.CharField(max_length=30, verbose_name='Eey')),
                ('eKey', models.CharField(max_length=30, verbose_name='eKey')),
                ('ADDR', models.CharField(max_length=30, verbose_name='ADDR')),
                ('MACaddress', models.CharField(max_length=30, null=True, verbose_name='MACaddress')),
                ('CCID', models.CharField(max_length=30, null=True, verbose_name='CCID')),
                ('RegTimes', models.DateTimeField(auto_now_add=True, verbose_name='RegTimes')),
                ('RecTimes', models.DateTimeField(auto_now=True, verbose_name='RecTimes')),
                ('BeatTimes', models.DateTimeField(auto_now=True, verbose_name='BeatTimes')),
            ],
            options={
                'verbose_name': 'deviceInfo',
                'verbose_name_plural': 'deviceInfo',
            },
        ),
        migrations.CreateModel(
            name='subclass_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Serial number')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('Devicename', models.CharField(max_length=30, verbose_name='Device name')),
                ('Areaname', models.CharField(max_length=120, verbose_name='Area name')),
                ('Devicenumber', models.IntegerField(max_length=10, verbose_name='Device number')),
                ('State', models.CharField(choices=[('to poy', 'to poy '), ('To be paid', 'To be paid'), ('Refund', 'Refund')], default='To be paid', max_length=10, verbose_name='State')),
                ('Type', models.CharField(choices=[('BANK', 'bank'), ('Alipay', 'alipay'), ('WeChat', 'wechat')], default='BANK', max_length=10, verbose_name='Transaction type')),
                ('Money', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount of money')),
                ('Duration', models.IntegerField(max_length=10, verbose_name='Transaction duration')),
                ('paymenttime', models.DateTimeField(auto_now_add=True, verbose_name='Payment time')),
                ('endtime', models.DateTimeField(auto_now=True, verbose_name='Payment time')),
                ('POnumber', models.IntegerField(max_length=20, verbose_name='Payment order number')),
                ('Remarks', models.TextField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('deviceInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xproject.DeviceInfo')),
            ],
            options={
                'verbose_name': 'subclass details',
                'verbose_name_plural': 'subclass details',
            },
        ),
        migrations.DeleteModel(
            name='ss',
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(null=True, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='device',
            field=models.IntegerField(max_length=8, null=True, verbose_name='device'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='room',
            field=models.IntegerField(max_length=8, null=True, verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='telphone',
            field=models.CharField(max_length=30, null=True, verbose_name='telphone'),
        ),
        migrations.AddField(
            model_name='subclass_details',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xproject.Organization'),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xproject.Organization'),
        ),
    ]
