# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-21 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xproject', '0004_auto_20181220_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['starttime'], 'verbose_name': 'price', 'verbose_name_plural': 'price'},
        ),
    ]
